/* eslint-disable @next/next/no-sync-scripts */
import Head from "next/head";
import Layout from "../components/Layout";
export default function Home() {
  return (
    <>
      <div>
        <Head>
          <title>HPX Deliver</title>
          <meta name="description" content="Generated by create next app" />
        </Head>
        <div>
          <Layout />
        </div>
      </div>
    </>
  );
}
